# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-13 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transformer',
            name='power_line',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operation.PowerLine'),
        ),
    ]
